language: generic
branches:
  only:
  - master
cache:
  directories:
  - vendor
sudo: required
services:
- docker
install:
- make bootstrap
script:
- make build
deploy:
- provider: script
  script: _scripts/deploy.sh
  on:
    branch: master
notifications:
  webhooks:
    urls:
      - secure: "Lu2Bp3tO7z+sli3P0hk6M17X9fclkv/q+CA+2WR8AH8bzZS2GhaEuXPY+5+x3NBnK52MZUaDefb4/9evfsAn0zHFRvFpma+o7zsQhc2a9kTdvF7cf4v+8zW3/VJkKlwfVn9EHH4PU+CL7UmPOvoABN4WbOpAWK+Qw3Ju6jMkBJAmvpBjvsUNuIzP5Yflx6yvtFcw+frlBOGYeflG4OltcrVtcRfNNHC2sDgYwVecicVnpoq+XuIEUOU6/R5XbtBrMmiy9hVGd00pHV1O+FLs4RutENgZe3/0ZokCe/THq+bpZzrekFfjViJGZ8hKNzhppOMQ4mOGcL2aVxJmCPxeEhdoCIv2eMG8bgcNW5PX2H4HToaBm0K9OpB1InmeSKRrpsJdNb2ioKYAXr4V6rmlltxl6rUigYpQXOeb8t/Fb6pVEbDeFhVIRRilrsUfSzEshzrDlWQ0udPdQuEA4nTEjntLxcyt0kftRbs3I65AMDAjDEtbmW0qTdn6+qV8x7LNMQUmnvxcjcq/kFL9nCFt8hpvCZa5O03k3F6qe+O/Zz4sBezLnJGcllZkJ02LPbpgk0LOrnWz3ZycO69GXp8u6ZAfEmF/skIBWOmoR1dF22iBiF28MUO7apFvdcVOzF5RvbHdX/BZAYf5zFgd4W21h7GyF39XqriAVCkV68B1n1k="
    on_success: always
    on_failure: never
    on_start: never
