language: generic
branches:
  only:
  - master
cache:
  directories:
  - vendor
sudo: required
services:
- docker
install:
- make bootstrap
script:
- make build
deploy:
- provider: script
  script: _scripts/deploy.sh
  on:
    branch: master
notifications:
  webhooks:
    urls:
      - https://ci.deis.io/job/deis-v2-e2e/build?token=${JENKINS_TOKEN}
    on_success: always
    on_failure: never
    on_start: never
env:
  global:
    - secure: "n+W9RKlaYmOJvIYUvrDuOgkjXAr7dGqdKAlbwJnsGu8g2g7g87Zo0HN6Mi/ozI247HAt7/uT7fw5AtDhrcjXkwBj/Q04dqYmO62Up4QFLIbkFV3JmJnc3lVtiWEEI2H7q5+ughcPLVCNQZ0sixLrM5h0TaY/b6VPdowuWzXAipMsVc0yHkr/olUnRtguDNyBOSAbRPRMR1ceuFAe4KhGDnYORpwxZNS0l0IJjki6MSxCWAmPhQJLQ5OyvLlZamjWcG/qzQedVrJi0fFXz47uhNrnbeyTlQ4AAwGtWacFjEeL75LRvNxznA6y+99Xj+vyJjOMHGkv1sQ6bHTyQsyxUjq2RrqLelysfwPmVeAMCMoWuYrFOsmoNJ7BEn7HbrEnC5vcl2xzmCyIH25L8igCFYLCtBAyov1kdUro9W/ygiQj4BElya2unNhgHYFQpn3wSKKXmiX9tSEbIxHApS2xlsHra68a8gt7nbQrTmUSncf5o4BagYfKf8iMVePRXZY7ZCqorUciY7D+tcEkQZGkK4orqTsEk5Gg4hi88uqc01idaGHPi1AWCAdqncAYIhQFrnYE3MpH/JVqTyIMyqKrsthtkzMEEjMZuPkp55SlSDmskhNytTA2DPnhCQhEP8LENwlpRofAK1pfkbDwYbhDVi/HKsT8xjASt4jEcvLiDq4="
